"""
Django settings for lung_cancer_screening project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
from os import environ
from pathlib import Path

from jinja2 import ChainableUndefined


def boolean_env(key, default=None):
    value = environ.get(key)
    return default if value is None else value in ("True", "true", "1")


def list_env(key):
    value = environ.get(key)
    return value.split(",") if value else []


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = boolean_env("DEBUG", default=False)

ALLOWED_HOSTS = list_env("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = list_env("CSRF_TRUSTED_ORIGINS")

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    "django.forms",
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lung_cancer_screening.core',
    'lung_cancer_screening.nhsuk_forms',
    'lung_cancer_screening.questions',
    'mozilla_django_oidc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lung_cancer_screening.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "DIRS": [BASE_DIR / "jinja2"],
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "lung_cancer_screening.jinja2_env.environment",
            "undefined": ChainableUndefined,
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lung_cancer_screening.wsgi.application'
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "lung_cancer_screening.config.postgresql",
        "NAME": environ.get("DATABASE_NAME", ""),
        "USER": environ.get("DATABASE_USER", ""),
        "PASSWORD": environ.get("DATABASE_PASSWORD", ""),
        "HOST": environ.get("DATABASE_HOST", ""),
        "PORT": environ.get("DATABASE_PORT", "5432"),
        "OPTIONS": {"sslmode": environ.get("DATABASE_SSLMODE", "prefer")},
    }
}

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "assets" / "compiled"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOG_QUERIES = boolean_env("LOG_QUERIES")
LOGGING = {
    "version": 1,  # the dictConfig format version
    "disable_existing_loggers": False,  # retain the default loggers
    "formatters": {
        "verbose": {
            "format": (
                "%(asctime)s [%(process)d] [%(levelname)s] "
                "[%(module)s] %(message)s"
            ),
            "datefmt": "[%Y-%m-%d %H:%M:%S %z]",
            "class": "logging.Formatter",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "stream": sys.stdout,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
    "loggers": {
        "django": {
            "level": "INFO",
            "handlers": ["console"],
            "propagate": False,
        },
        "django.db.backends": {
            "level": "DEBUG" if LOG_QUERIES else "INFO",
            "handlers": ["console"],
            "propagate": False,
        },
        "django.server": {
            "level": "INFO",
            "handlers": ["console"],
            "propagate": False,
        },
        "django.utils.autoreload": {
            "level": "INFO",
            "handlers": ["console"],
            "propagate": False,
        },
        "faker": {"level": "INFO"},
    },
}

# Custom User Model
AUTH_USER_MODEL = 'questions.User'

# OIDC Client Configuration for NHS Login
# See: https://mozilla-django-oidc.readthedocs.io/
OIDC_RP_CLIENT_ID = environ.get("OIDC_RP_CLIENT_ID")
# Private key JWT authentication (no client secret)
# Set a dummy value to satisfy mozilla-django-oidc's requirement
# It w't be used since we override get_token() to use private key JWT
OIDC_RP_CLIENT_SECRET = "not-used-private-key-jwt"
OIDC_RP_CLIENT_PRIVATE_KEY = environ.get("OIDC_RP_CLIENT_PRIVATE_KEY")
OIDC_OP_FQDN = environ.get("OIDC_OP_FQDN")
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{OIDC_OP_FQDN}/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"{OIDC_OP_FQDN}/token"
OIDC_OP_USER_ENDPOINT = f"{OIDC_OP_FQDN}/userinfo"
OIDC_OP_JWKS_ENDPOINT = f"{OIDC_OP_FQDN}/.well-known/jwks.json"
# NHS Login requires RS512 for token endpoint authentication
# See: https://auth.sandpit.signin.nhs.uk/.well-known/openid-configuration
OIDC_RP_SIGN_ALGO = "RS512"
OIDC_RP_SCOPES = "openid profile profile_extended email"
OIDC_RP_REDIRECT_URI = f"{environ.get('BASE_URL')}/oidc/callback/"
# Use custom auth request view so redirect_uri is BASE_URL, not request Host
# (fixes post-login redirect to instance URL when behind Front Door / proxy).
OIDC_AUTHENTICATE_CLASS = (
    "lung_cancer_screening.questions.views.oidc_auth.NHSLoginAuthenticationRequestView"
)
NHS_LOGIN_SETTINGS_URL = environ.get("NHS_LOGIN_SETTINGS_URL")

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'lung_cancer_screening.questions.auth.NHSLoginOIDCBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Login settings
LOGIN_URL = '/oidc/authenticate/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL_FAILURE = "/agree-to-share-information"
ALLOW_LOGOUT_GET_METHOD = True

# Additional security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    USE_X_FORWARDED_HEADERS = True

DISABLE_RECENT_SUBMISSION_LIMITATION = boolean_env("DISABLE_RECENT_SUBMISSION_LIMITATION", default=False)
