@startuml

actor "Participant" as Participant
entity "LCS App" as LCS_App
entity "NHS login" as NHS_Login
entity "In Health" as InHealth
entity "NHS Incentivisation system" as NHS_Incentivisation_System

' Date flow into LCS App
Participant -> LCS_App
LCS_App -> NHS_Login
NHS_Login -> LCS_App: Participant logs in and shares profile, email address and NHS Number (scopes "openid profile email") with LCS app
Participant -> LCS_App: Completes questionnaire

' Data flow from LCS App to In Health
LCS_App -> InHealth: Completed digital participant NHS Numbers shared with InHealth
InHealth -> LCS_App: InHealth share completed telephone responses corresponding to digital NHS number responses

' Data flow from LCS App to NHS Incentivisation system
LCS_App -> NHS_Incentivisation_System: Eligible participant's email addresses shared with NHS Incentivisation system
NHS_Incentivisation_System -> Participant: Participant is incentivised
