@startuml
actor "NHSE pilot admin staff actor" as NHSE_Admin
actor "NHSE analysis staff actor" as NHSE_Analysis
entity "NHS digital pilot lung risk app" as NHS_LR_App
database "NHSE Lung Anonymised database" as Lung_Anon_DB
actor "GP staff actor" as GP_Staff
entity "GP system" as GP_System
database "GP System Identifiable database" as GP_ID_DB
actor "e2e partner staff actor" as E2E_Staff
entity "e2e partner system" as E2E_System
database "e2e partner Identifiable database" as E2E_ID_DB
database "e2e partner Pilot Lookup database" as E2E_Pilot_Lookup_DB
actor "participant actor" as Participant

' Step 1 BAU lung cohorting
GP_Staff -> GP_System: Request BAU Lung Screening Cohort extract
GP_System -> GP_ID_DB: Request BAU Lung Screening Cohort information
GP_ID_DB --> GP_System: Provide BAU Lung Screening Cohort information
GP_System -> GP_System: Create BAU Lung Screening Cohort extract
GP_System --> GP_Staff: Provide BAU Lung Screening Cohort extract
GP_Staff -> E2E_Staff: (LUNGDF100) Provide BAU Lung Screening Cohort extract
E2E_Staff -> E2E_System: Upload BAU Lung Screening Cohort extract
E2E_System -> E2E_ID_DB: Store BAU Lung Screening Cohort extract
' Step 2 pilot digital app cohorting and consent
NHSE_Admin -> NHSE_Admin: Identify required cohort size (e.g. 50 participants)
NHSE_Admin -> E2E_Staff: Advise required cohort size
E2E_Staff -> Participant: Ask for consent to join pilot

alt Participant provides consent
    Participant -> E2E_Staff: Provide consent
    E2E_Staff -> E2E_System: Record consent
    E2E_System -> E2E_System: Generate unique Pilot ID for NHS Number
    E2E_System -> E2E_Pilot_Lookup_DB: Record NHS Number, Pilot ID and consent
    E2E_Staff -> NHSE_Admin: (LUNGDF200) Send Pilot ID participant list
    NHSE_Admin -> Lung_Anon_DB: Upload consented Pilot ID participant list
    E2E_Staff -> Participant: Provide access details for NHS digital pilot app
' Step 3 participant completion of pilot digital app journey
    Participant -> NHS_LR_App: Enter Pilot ID
    NHS_LR_App -> NHS_LR_App: Verify participant is consented user
    Participant -> NHS_LR_App: Answer digital risk assessment questions
    NHS_LR_App -> Lung_Anon_DB: Store Pilot ID, digital risk assessment answers
    NHSE_Admin -> Lung_Anon_DB: Request Pilot IDs who have completed digital risk assessment questions
    Lung_Anon_DB --> NHSE_Admin: Response for Pilot IDs who have completed digital risk assessment questions
    NHSE_Admin -> E2E_Staff: (LUNGDF300) Advise of completed digital risk assessment Pilot IDs
    E2E_Staff -> E2E_Pilot_Lookup_DB: Request NHS Number for Pilot ID
    E2E_Pilot_Lookup_DB --> E2E_Staff: Response NHS Number for Pilot ID
' Step 4 BAU telephone user journey
    E2E_Staff -> Participant: Contact participant for BAU telephone journey risk assessment
    Participant -> E2E_Staff: Complete BAU telephone journey risk assessment
    E2E_Staff -> E2E_System: Capture BAU telephone journey risk assessment
    E2E_System -> E2E_ID_DB: Capture BAU telephone journey risk assessment
' Step 5 prepare data and analyse
    E2E_System -> E2E_System: Anonymise BAU telephone journey answers
    E2E_System -> NHSE_Admin: (LUNGDF400) Provide anonymised BAU telephone journey answers
    NHSE_Admin -> Lung_Anon_DB: Upload anonymised BAU telephone journey answers
    NHS_LR_App -> Lung_Anon_DB: Access identifiable online digital risk assessment answers
    NHS_LR_App -> NHS_LR_App: Create anonymised online digital risk assessment answers
    NHS_LR_App -> Lung_Anon_DB: Upload anonymised online digital risk assessment answers
    NHSE_Analysis -> Lung_Anon_DB: Analyse anonymised data
else Participant does NOT provide consent
    Participant -> E2E_Staff: Do not provide consent
    E2E_Staff -> E2E_System: Record non-consent
    note over E2E_System: End of sequence — no further actions
end
@enduml
