ENVIRONMENT=poc
ENV_CONFIG=poc
AZURE_SUBSCRIPTION="Lung Cancer Screening - Dev"
HUB_SUBSCRIPTION="Lung Cancer Screening - Dev"
STORAGE_ACCOUNT_RG=rg-tfstate-poc-uks
TERRAFORM_MODULES_REF=main
ENABLE_SOFT_DELETE=false
DOCKER_IMAGE=ghcr.io/nhsdigital/lung_cancer_screening
OIDC_RP_CLIENT_ID="lcrc"
OIDC_OP_FQDN="https://auth.sandpit.signin.nhs.uk"
