ENVIRONMENT=poc
ENV_CONFIG=poc
AZURE_SUBSCRIPTION="Lung Cancer Screening - Dev"
HUB_SUBSCRIPTION="Lung Cancer Screening - Dev"
STORAGE_ACCOUNT_RG=rg-tfstate-poc-uks
TERRAFORM_MODULES_REF=main
ENABLE_SOFT_DELETE=false
DOCKER_IMAGE=docker.io/nginxdemos/hello
DOCKER_IMAGE_TAG=latest
