# Generated by Django 5.2.11 on 2026-02-11 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tobaccosmokinghistory',
            name='unique_tobacco_smoking_history_per_response_set',
        ),
        migrations.AddField(
            model_name='tobaccosmokinghistory',
            name='level',
            field=models.CharField(choices=[('normal', 'Normal'), ('increased', 'Increased'), ('decreased', 'Decreased')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='smokedamountresponse',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='tobaccosmokinghistory',
            constraint=models.UniqueConstraint(fields=('response_set', 'type', 'level'), name='unique_tobacco_smoking_history_per_response_set_and_type_and_level', violation_error_message='A tobacco smoking history already exists for this response set, type and level'),
        ),
    ]
