# Generated by Django 5.2.11 on 2026-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_tobaccosmokinghistory_unique_tobacco_smoking_history_per_response_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobaccosmokinghistory',
            name='level',
            field=models.CharField(choices=[('normal', 'Normal'), ('increased', 'Yes, I used to smoke more'), ('decreased', 'Yes, I used to smoke fewer'), ('stopped', 'Yes, I stopped smoking for a period of 1 year or longer'), ('no_change', 'No, it has not changed')], default='normal', max_length=20),
        ),
    ]
