# Generated by Django 5.2.4 on 2025-09-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_booleanresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='BooleanResponse',
            name='question',
            field=models.CharField(default='Have you ever smoked?', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='QuestionnaireResponse',
            name='question',
            field=models.CharField(default='What is your date of birth?', max_length=255),
            preserve_default=False,
        ),
    ]
