# Generated by Django 5.2.11 on 2026-02-28 22:01

from django.db import migrations, models


def rolled_cigarettes_to_rolling_tobacco(apps, schema_editor):
    TobaccoSmokingHistory = apps.get_model('questions', 'TobaccoSmokingHistory')
    TobaccoSmokingHistory.objects.filter(type='RolledCigarettes').update(type='RollingTobacco')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_tobaccosmokinghistory_level'),
    ]

    operations = [
        migrations.RunPython(rolled_cigarettes_to_rolling_tobacco, noop),
        migrations.AlterField(
            model_name='tobaccosmokinghistory',
            name='level',
            field=models.CharField(choices=[('normal', 'Normal'), ('increased', 'Yes, I used to smoke more'), ('decreased', 'Yes, I used to smoke fewer'), ('no_change', 'No, it has not changed')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='tobaccosmokinghistory',
            name='type',
            field=models.CharField(choices=[('Cigarettes', 'Cigarettes'), ('RollingTobacco', 'Rolling tobacco'), ('Pipe', 'Pipe'), ('Cigars', 'Cigars'), ('Cigarillos', 'Cigarillos'), ('Shisha', 'Shisha')]),
        ),
    ]
