# Generated by Django 5.2.4 on 2025-09-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_booleanresponse_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionnaireResponse',
            new_name='DateResponse',
        ),

    ]
