# Generated by Django 5.2.11 on 2026-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_tobaccosmokinghistory_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobaccosmokinghistory',
            name='type',
            field=models.CharField(choices=[('Cigarettes', 'Cigarettes'), ('RollingTobacco', 'Rolling tobacco'), ('Pipe', 'Pipe'), ('SmallCigars', 'Small cigars'), ('MediumCigars', 'Medium cigars'), ('LargeCigars', 'Large cigars'), ('Cigarillos', 'Cigarillos')]),
        ),
    ]
