# Generated by Django 5.2.6 on 2025-09-08 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_questionnaireresponse_to_dateresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_you_ever_smoked', models.IntegerField(choices=[(0, 'Yes, I currently smoke'), (1, 'Yes, I used to smoke regularly'), (2, 'Yes, but only a few times'), (3, 'No, I have never smoked')], null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.participant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
