# Generated by Django 5.2.6 on 2025-09-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_responseset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooleanResponse',
        ),
        migrations.DeleteModel(
            name='DateResponse',
        ),
    ]
