# Generated by Django 5.2.11 on 2026-03-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_tobaccosmokinghistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokingfrequencyresponse',
            name='value',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1),
        ),
    ]
