# Generated by Django 5.2.6 on 2025-09-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_dateresponse_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='responseset',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responseset',
            name='have_you_ever_smoked',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes, I currently smoke'), (1, 'Yes, I used to smoke regularly'), (2, 'Yes, but only a few times'), (3, 'No, I have never smoked')], null=True),
        ),
    ]
