# Generated by Django 5.2.11 on 2026-03-09 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_smokingfrequencyresponse_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.BooleanField()),
                ('response_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_of_use_response', to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
