# Generated by Django 5.2.6 on 2025-09-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_responseset_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseset',
            name='submitted',
        ),
        migrations.AddField(
            model_name='responseset',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
