# Generated by Django 6.0.3 on 2026-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_termsofuseresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderresponse',
            name='value',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-binary'), ('P', 'Prefer not to say')], max_length=1),
        ),
    ]
