# Generated by Django 5.2.6 on 2025-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_responseset_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
