# Generated by Django 6.0.3 on 2026-03-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_genderresponse_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexatbirthresponse',
            name='value',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='nhs_number',
            field=models.CharField(max_length=10),
        ),
    ]
