# Generated by Django 6.0.3 on 2026-03-31 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_sexatbirthresponse_value_alter_user_nhs_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhenYouQuitSmokingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
                ('response_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
