# Generated by Django 6.0.3 on 2026-03-31 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_whenyouquitsmokingresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whenyouquitsmokingresponse',
            name='response_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='when_you_quit_smoking_response', to='questions.responseset'),
        ),
    ]
