# Generated by Django 5.2.7 on 2025-10-21 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_responseset_height_imperial_alter_responseset_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='weight_metric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responseset',
            name='height_imperial',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(55, message='Height must be between 4 feet 7 inches and 8 feet'), django.core.validators.MaxValueValidator(96, message='Height must be between 4 feet 7 inches and 8 feet')]),
        ),
    ]
