# Generated by Django 5.2.7 on 2025-10-27 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_responseset_weight_metric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='weight_imperial',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(56, message='Weight must be between 4 stone and 50 stone'), django.core.validators.MaxValueValidator(700, message='Weight must be between 4 stone and 50 stone')]),
        ),
        migrations.AlterField(
            model_name='responseset',
            name='weight_metric',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(254, message='Weight must be between 25.4kg and 317.5kg'), django.core.validators.MaxValueValidator(3175, message='Weight must be between 25.4kg and 317.5kg')]),
        ),
    ]
