# Generated by Django 6.0.4 on 2026-04-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_whenyouquitsmokingresponse_value_incentivised'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incentivised',
            name='questions_incentivised_unique_user',
        ),
        migrations.AddConstraint(
            model_name='incentivised',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_incentive_per_user'),
        ),
    ]
