# Generated by Django 5.2.7 on 2025-10-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_responseset_weight_imperial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='sex_at_birth',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
    ]
