# Generated by Django 5.2.7 on 2025-10-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_responseset_sex_at_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('P', 'Prefer not to say'), ('G', 'How I describe myself may not match my GP record')], max_length=1, null=True),
        ),
    ]
