# Generated by Django 5.2.7 on 2025-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_responseset_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('A', 'Asian or Asian British'), ('B', 'Black, African, Caribbean or Black British'), ('M', 'Mixed or multiple ethnic groups'), ('W', 'White'), ('O', 'Other ethnic group'), ('N', "I'd prefer not to say")], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='responseset',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-binary'), ('P', 'Prefer not to say'), ('G', 'How I describe myself may not match my GP record')], max_length=1, null=True),
        ),
    ]
