# Generated by Django 5.2.8 on 2025-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_responseset_ethnicity_alter_responseset_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='asbestos_exposure',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
