# Generated by Django 5.2.7 on 2025-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_responseset_asbestos_exposure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseset',
            name='asbestos_exposure',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
