# Generated by Django 5.2.8 on 2025-11-14 11:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_responseset_asbestos_exposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='respiratory_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('P', 'Pneumonia'), ('E', 'Emphysema'), ('B', 'Chronic bronchitis'), ('T', 'Tuberculosis (TB)'), ('C', 'Chronic obstructive pulmonary disease (COPD)'), ('N', 'None of the above')], max_length=1), blank=True, null=True, size=None),
        ),
    ]
