# Generated by Django 5.2.9 on 2025-12-09 16:06

import django.contrib.postgres.fields
import django.db.models.deletion
import lung_cancer_screening.questions.models.response_set
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responseset',
            name='have_you_ever_smoked',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes, I currently smoke'), (1, 'Yes, I used to smoke'), (2, 'Yes, but I have smoked fewer than 100 cigarettes in my lifetime'), (3, 'No, I have never smoked')], null=True),
        ),
        migrations.AlterField(
            model_name='responseset',
            name='respiratory_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('P', 'Pneumonia'), ('E', 'Emphysema'), ('B', 'Bronchitis'), ('T', 'Tuberculosis (TB)'), ('C', 'Chronic obstructive pulmonary disease (COPD)'), ('N', 'No, I have not had any of these respiratory conditions')], max_length=1), blank=True, null=True, size=None, validators=[lung_cancer_screening.questions.models.validators.singleton_option.validate_singleton_option]),
        ),
    ]
