# Generated by Django 5.2.9 on 2025-12-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_responseset_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseset',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
