# Generated by Django 5.2.9 on 2025-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_remove_responseset_participant_delete_participant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='responseset',
            name='unique_unsubmitted_response_per_participant',
        ),
        migrations.AddConstraint(
            model_name='responseset',
            constraint=models.UniqueConstraint(condition=models.Q(('submitted_at__isnull', True)), fields=('user',), name='unique_unsubmitted_response_per_user', violation_error_message='An unsubmitted response set already exists for this user'),
        ),
    ]
