# Generated by Django 5.2.9 on 2025-12-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_remove_responseset_unique_unsubmitted_response_per_participant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responseset',
            old_name='height',
            new_name='height_metric',
        ),
    ]
