# Generated by Django 5.2.9 on 2025-12-18 17:15

import django.db.models.deletion
from django.db import migrations, models


def copy_have_you_ever_smoked_data(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            INSERT INTO questions_haveyoueversmokedresponse (created_at, updated_at, value, response_set_id)
            SELECT NOW(), NOW(), have_you_ever_smoked, id
            FROM questions_responseset
            WHERE have_you_ever_smoked IS NOT NULL
            ON CONFLICT (response_set_id) DO NOTHING
        """)


def reverse_copy_have_you_ever_smoked_data(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE questions_responseset rs
            SET have_you_ever_smoked = h.value
            FROM questions_haveyoueversmokedresponse h
            WHERE rs.id = h.response_set_id
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_add_email_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaveYouEverSmokedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(choices=[(0, 'Yes, I currently smoke'), (1, 'Yes, I used to smoke'), (2, 'Yes, but I have smoked fewer than 100 cigarettes in my lifetime'), (3, 'No, I have never smoked')])),
                ('response_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(copy_have_you_ever_smoked_data, reverse_copy_have_you_ever_smoked_data),
        migrations.RemoveField(
            model_name='responseset',
            name='have_you_ever_smoked',
        ),
    ]
