# Generated by Django 5.2.9 on 2025-12-30 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0033_weightresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haveyoueversmokedresponse',
            name='response_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='have_you_ever_smoked_response', to='questions.responseset'),
        ),
    ]
