# Generated by Django 5.2.9 on 2026-01-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0035_cancerdiagnosisresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHistoryLungCancerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'I do not know')], max_length=1)),
                ('response_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_history_lung_cancer', to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
