# Generated by Django 5.2.9 on 2026-01-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_familyhistoryagewhendiagnosedresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelativesAgeWhenDiagnosedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('Y', 'Yes, they were younger than 60'), ('N', 'No, they were 60 or older'), ('U', 'I do not know')], max_length=1)),
                ('response_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatives_age_when_diagnosed', to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FamilyHistoryAgeWhenDiagnosedResponse',
        ),
    ]
