# Generated by Django 5.2.9 on 2026-01-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_relativesagewhendiagnosedresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckNeedAppointmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.BooleanField()),
                ('response_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_need_appointment_response', to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
