# Generated by Django 5.2.9 on 2026-01-09 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_relativesagewhendiagnosedresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('X', 'I finished school before the age of 15'), ('G', 'GCSEs'), ('A', 'A-levels'), ('B', "Bachelor's degree"), ('P', 'Postgraduate degree'), ('N', "I'd prefer not to say")], max_length=1)),
                ('response_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_response', to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
