# Generated by Django 5.2.10 on 2026-01-19 10:47

import django.contrib.postgres.fields
import lung_cancer_screening.questions.models.validators.singleton_option
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0041_alter_educationresponse_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationresponse',
            name='value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('X', 'I finished school before the age of 15'), ('G', 'GCSEs'), ('A', 'A-levels'), ('F', 'Further education'), ('B', "Bachelor's degree"), ('P', 'Postgraduate degree'), ('N', 'Prefer not to say')], max_length=1), size=None, validators=[lung_cancer_screening.questions.models.validators.singleton_option.validate_singleton_option]),
        ),
    ]
