# Generated by Django 5.2.10 on 2026-01-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0042_alter_educationresponse_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeWhenStartedSmokingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField()),
                ('response_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='age_when_started_smoking_response', to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
