# Generated by Django 5.2.10 on 2026-01-26 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_agewhenstartedsmokingresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agewhenstartedsmokingresponse',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='The age you started smoking must be between 1 and your current age')]),
        ),
        migrations.AlterField(
            model_name='ethnicityresponse',
            name='value',
            field=models.CharField(choices=[('A', 'Asian or Asian British'), ('B', 'Black, African, Caribbean or Black British'), ('M', 'Mixed or multiple ethnic groups'), ('W', 'White'), ('O', 'Other ethnic group'), ('N', 'Prefer not to say')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sexatbirthresponse',
            name='value',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('I', 'Intersex')], max_length=1),
        ),
        migrations.CreateModel(
            name='CurrentlySmokingCigarettesResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.BooleanField()),
                ('response_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currently_smoking_cigarettes_response', to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
