# Generated by Django 5.2.10 on 2026-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0044_periodswhenyoustoppedsmokingresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodswhenyoustoppedsmokingresponse',
            name='duration_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
