# Generated by Django 5.2.10 on 2026-01-21 16:57

import django.contrib.postgres.fields
import django.db.models.deletion
import lung_cancer_screening.questions.models.validators.singleton_option
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0045_periodswhenyoustoppedsmokingresponse_duration_years"),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesTobaccoSmokingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'Cigarettes'), ('G', 'Cigars'), ('P', 'Pipes'), ('E', 'E-cigarettes or vaping'), ('N', 'None of the above')], max_length=1), size=None, validators=[lung_cancer_screening.questions.models.validators.singleton_option.validate_singleton_option])),
                ('response_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='types_tobacco_smoking_response', to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
