# Generated by Django 5.2.10 on 2026-01-27 14:59

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0046_alter_ethnicityresponse_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agewhenstartedsmokingresponse',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='The age you started smoking must be between 1 and your current age')]),
        ),
        migrations.AlterField(
            model_name='ethnicityresponse',
            name='value',
            field=models.CharField(choices=[('A', 'Asian or Asian British'), ('B', 'Black, African, Caribbean or Black British'), ('M', 'Mixed or multiple ethnic groups'), ('W', 'White'), ('O', 'Other ethnic group'), ('N', 'Prefer not to say')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sexatbirthresponse',
            name='value',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('I', 'Intersex')], max_length=1),
        ),
        migrations.AlterField(
            model_name='typestobaccosmokingresponse',
            name='value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'Cigarettes'), ('R', 'Rolled cigarettes, or roll-ups'), ('P', 'Pipe'), ('G', 'Cigars'), ('E', 'Cigarillos'), ('S', 'Shisha')], max_length=1), size=None),
        ),
    ]
