# Generated by Django 5.2.10 on 2026-01-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0047_alter_agewhenstartedsmokingresponse_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TobaccoSmokingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Cigarettes', 'Cigarettes'), ('RolledCigarettes', 'Rolled cigarettes, or roll-ups'), ('Pipe', 'Pipe'), ('Cigars', 'Cigars'), ('Cigarillos', 'Cigarillos'), ('Shisha', 'Shisha')])),
                ('response_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_tobacco_smoking', to='questions.responseset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TypesTobaccoSmokingResponse',
        ),
    ]
