# Generated by Django 5.2.10 on 2026-01-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0048_tobaccosmokinghistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokedTotalYearsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tobaccosmokinghistory',
            name='response_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobacco_smoking_history', to='questions.responseset'),
        ),
        migrations.AddConstraint(
            model_name='tobaccosmokinghistory',
            constraint=models.UniqueConstraint(fields=('response_set', 'type'), name='unique_tobacco_smoking_history_per_response_set', violation_error_message='A tobacco smoking history already exists for this response set and type'),
        ),
        migrations.AddField(
            model_name='smokedtotalyearsresponse',
            name='tobacco_smoking_history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smoked_total_years_response', to='questions.tobaccosmokinghistory'),
        ),
    ]
