# Generated by Django 5.2.10 on 2026-02-03 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0049_smokedtotalyearsresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodswhenyoustoppedsmokingresponse',
            name='duration_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='The number of years you stopped smoking for must be at least 1')]),
        ),
        migrations.AlterField(
            model_name='smokedtotalyearsresponse',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='The number of years you smoked cigarettes must be at least 1')]),
        ),
    ]
