# Generated by Django 5.2.11 on 2026-02-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0050_alter_periodswhenyoustoppedsmokingresponse_duration_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokingCurrentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.BooleanField()),
                ('tobacco_smoking_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smoking_current_response', to='questions.tobaccosmokinghistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
