# Generated by Django 5.2.11 on 2026-02-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0051_smokingcurrentresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokingFrequencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1)),
                ('tobacco_smoking_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smoking_frequency_response', to='questions.tobaccosmokinghistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
