# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0053_smokedamountresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='given_name',
            field=models.CharField(blank=False, null=False, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=False, null=False, max_length=255),
        ),
    ]
