# Generated by Django 5.2.11 on 2026-02-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0054_add_given_name_and_family_name_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(max_length=255, unique=True)
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
