name: "Test stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string
      nodejs_version:
        description: "Node.js version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      terraform_version:
        description: "Terraform version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  build-compose-cache:
    name: "Build Docker Compose cache"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
      - name: "Build asset_builder for cache"
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          target: asset_builder
          push: false
          load: true
          tags: ${{ github.event.repository.name }}_asset_builder:latest
          cache-from: type=gha,scope=compose-asset
          cache-to: type=gha,scope=compose-asset,mode=max
      - name: "Build web image for cache"
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          target: development
          push: false
          load: true
          tags: ${{ github.event.repository.name }}_web:latest
          cache-from: type=gha,scope=compose-web
          cache-to: type=gha,scope=compose-web,mode=max

  test-unit:
    name: "Unit tests"
    needs: [build-compose-cache]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
      - name: "Build asset_builder from cache"
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          target: asset_builder
          push: false
          load: true
          tags: ${{ github.event.repository.name }}_asset_builder:latest
          cache-from: type=gha,scope=compose-asset
          cache-to: type=gha,scope=compose-asset,mode=max
      - name: "Build web image from cache"
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          target: development
          push: false
          load: true
          tags: ${{ github.event.repository.name }}_web:latest
          cache-from: type=gha,scope=compose-web
          cache-to: type=gha,scope=compose-web,mode=max
      - name: "Run unit test suite"
        env:
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
          COMPOSE_PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          cp .env.example .env
          make test-unit
      - name: "Save the result of fast test suite"
        run: |
          echo "Nothing to save"
  test-lint:
    name: "Linting"
    needs: [build-compose-cache]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
      - name: "Build asset_builder from cache"
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          target: asset_builder
          push: false
          load: true
          tags: ${{ github.event.repository.name }}_asset_builder:latest
          cache-from: type=gha,scope=compose-asset
          cache-to: type=gha,scope=compose-asset,mode=max
      - name: "Build web image from cache"
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          target: development
          push: false
          load: true
          tags: ${{ github.event.repository.name }}_web:latest
          cache-from: type=gha,scope=compose-web
          cache-to: type=gha,scope=compose-web,mode=max
      - name: "Run linting"
        env:
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
          COMPOSE_PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          cp .env.example .env
          make test-lint
      - name: "Save the linting result"
        run: |
          echo "Nothing to save"
  test-features:
    name: "Feature tests"
    needs: [build-compose-cache]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
      - name: "Build asset_builder from cache"
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          target: asset_builder
          push: false
          load: true
          tags: ${{ github.event.repository.name }}_asset_builder:latest
          cache-from: type=gha,scope=compose-asset
          cache-to: type=gha,scope=compose-asset,mode=max
      - name: "Build web image from cache"
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          target: development
          push: false
          load: true
          tags: ${{ github.event.repository.name }}_web:latest
          cache-from: type=gha,scope=compose-web
          cache-to: type=gha,scope=compose-web,mode=max
      - name: "Run feature tests"
        env:
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
          COMPOSE_PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          cp .env.example .env
          make test-features
      - name: "Save result"
        run: |
          echo "Nothing to save"
  test-coverage:
    name: "Test coverage"
    needs: [test-unit]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: "Run test coverage check"
        run: |
          make test-coverage
      - name: "Save the coverage check result"
        run: |
          echo "Nothing to save"
  perform-static-analysis:
    name: "Perform static analysis"
    needs: [test-unit]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0 # Full history is needed to improving relevancy of reporting
      - name: "Perform static analysis"
        uses: ./.github/actions/perform-static-analysis
        with:
          sonar_organisation_key: "${{ vars.SONAR_ORGANISATION_KEY }}"
          sonar_project_key: "${{ vars.SONAR_PROJECT_KEY }}"
          sonar_token: "${{ secrets.SONAR_TOKEN }}"
