name: test

on:
  workflow_dispatch:

env:
  TARGET_ENV: poc

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: ${{ env.TARGET_ENV }}
    concurrency: deploy-${{ env.TARGET_ENV }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: 1.11.4

      - name: Terraform init
        run: |
          make ${TARGET_ENV} terraform-init
